### ISSUE TITLE
Permission denied 'custom_icons/'

### ISSUE THREAD

**Issue by jclusso** [Armaell/home-assistant-custom-icons-loader#4]
I can't get this working. I get this error on startup.

`2020-05-04 12:00:01 ERROR (MainThread) [homeassistant.setup] Error during setup of component custom_icons
  8 Traceback (most recent call last):
  9   File "/usr/local/lib/python3.7/site-packages/homeassistant/setup.py", line 171, in _async_setup_component
 10     hass, processed_config
 11   File "/Users/jarrett/.homeassistant/custom_components/custom_icons/__init__.py", line 10, in async_setup
 12     if parser.checkIfNeeded():
 13   File "/Users/jarrett/.homeassistant/custom_components/custom_icons/parser.py", line 62, in checkIfNeeded
 14     mkdir(ICONS_PATH)
 15 PermissionError: [Errno 13] Permission denied: 'custom_icons/'
 16 2020-05-04 12:00:01 ERROR (MainThread) [hacs] Could not set logging level to debug, logger is not enabled
 17 2020-05-04 12:00:01 ERROR (MainThread) [homeassistant.components.fan] Error while setting up homekit_controller platform for fan
 18 Traceback (most recent call last):
 19   File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 186, in _async_setup_platform
 20     await asyncio.gather(*pending)
 21   File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 295, in async_add_entities
 22     await asyncio.gather(*tasks)
 23   File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 445, in _async_add_entity
 24     entity.async_write_ha_state()
 25   File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 297, in async_write_ha_state
 26     self._async_write_ha_state()  # type: ignore
 27   File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 323, in _async_write_ha_state
 28     attr.update(self.state_attributes or {})
 29   File "/usr/local/lib/python3.7/site-packages/homeassistant/components/fan/__init__.py", line 180, in state_attributes
 30     if not hasattr(self, prop):
 31   File "/usr/local/lib/python3.7/site-packages/homeassistant/components/homekit_controller/fan.py", line 91, in current_direction
 32     return HK_DIRECTION_TO_HA[direction]
 33 KeyError: None`

**Comment by Larx** [comment]
Is there any solution for this problem? I have the same situation.
